### ISSUE TITLE
[SUGESTÃO] Criação de ONG

### ISSUE THREAD

**Issue by era** [CodeClubBrasil/CodeClubBrasil.github.io#9]
Olá pessoal,

Estava pesquisando um pouco sobre instituições de caridade que estão ensinando sobre programação a crianças e me deparei com o CodeClub. Pelo que entendi, o CodeClubBrasil, é na verdade uma tradução do CodeClub original, mantendo inclusive o """CNPJ""" britanico, certo?

Não seria interessante a criação de uma ONG (não sei se é o mais adequado, mas mais infos aqui: http://revife.com/2011/01/31/ong-o-que-e-como-criar-e-administrar/)?  Assim a coisa fica mais transparente e possibilita até o abatimento no IR de quem doar, pois acho que se encaixaria no ECA, não? (http://exame.abril.com.br/seu-dinheiro/noticias/que-tal-fazer-uma-doacao-em-vez-de-pagar-imposto-de-renda).

Efim, só uma sugestão. Até pq dá trabalho, envolve uma super dedicação que eu mesmo não pegaria para mim :(.

E obrigado a todos os voluntários que traduziram o material ou estão dando aulas <3.

**Comment by lgmoneda** [comment]
Hey, Elias! Tudo bem? Valeu pelo interesse, muito legal!

Na verdade, estamos justamente nesse processo :)

Acompanhe a gente mais de perto através da página do Facebook e do grupo! Caso queira contribuir com a coordenação, tradução ou ser instrutor de um clube, é só falar com a gente por lá também.

https://www.facebook.com/CodeClubBrasil
https://www.facebook.com/groups/CodeClubBrasil/

**Comment by era** [comment]
Olá Luis, tudo bem?

Ah, que legal que já tá rolando isso então. Vou dar like lá no facebook para acompanhar e ver se posso colaborar com algo. Obrigado :)

**Comment by lgmoneda** [comment]
Pode mandar mensagem direta pra página ou me adicionar: Luis Gustavo
Moneda!
